### PR TITLE
Fix issue related to quality with png

### LINKED ISSUE #27: options.quality is unsupported for the png screenshots
I think this line cause trouble when I try to get a `png`:
https://github.com/frinyvonnick/node-html-to-image/blob/06f16e791eb026460c11394387cab95aee3ba144/src/index.js#L9

I got this error:
```
Error: options.quality is unsupported for the png screenshots
    at assert (/app/node_modules/puppeteer/lib/helper.js:283:11)
    at Page.screenshot (/app/node_modules/puppeteer/lib/Page.js:903:7)
    at Page. (/app/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.screenshot (/app/node_modules/puppeteer/lib/JSHandle.js:449:40)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/app/node_modules/node-html-to-image/src/index.js:26:18)
    at async Object.postToInstagram (/app/plugins/MyApp/services/MyApp.js:1043:20)
    at async Object.postToInsta (/app/api/cdn/controllers/cdn.js:148:5)
    at async /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:77:22
    at async module.exports (/app/api/cdn/config/policies/isAdmin.js:4:12)
    at async module.exports (/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:112:3)
    at async /app/node_modules/strapi-utils/lib/policy.js:52:5
    at async serve (/app/node_modules/koa-static/index.js:59:5)
    at async strapi.router.get.koaStatic.maxage (/app/node_modules/strapi/lib/middlewares/public/index.js:92:11)
    at async evalmachine.:70:11
  -- ASYNC --
    at ElementHandle. (/app/node_modules/puppeteer/lib/helper.js:111:15)
    at module.exports (/app/node_modules/node-html-to-image/src/index.js:26:32)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.postToInstagram (/app/plugins/MyApp/services/MyApp.js:1043:20)
    at async Object.postToInsta (/app/api/cdn/controllers/cdn.js:148:5)
    at async /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:77:22
    at async module.exports (/app/api/cdn/config/policies/isAdmin.js:4:12)
    at async module.exports (/app/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:112:3)
    at async /app/node_modules/strapi-utils/lib/policy.js:52:5
    at async serve (/app/node_modules/koa-static/index.js:59:5)
    at async strapi.router.get.koaStatic.maxage (/app/node_modules/strapi/lib/middlewares/public/index.js:92:11)
    at async evalmachine.:70:11
```

### PR DESCRIPTION
**Pull request by Heziode**
Close #27

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ module.exports = async function({
   output,
   type,
   content,
-  quality = 80, // only applicable for jpg
+  quality = undefined,
```
Comment (frinyvonnick) [inline src/index.js:9]: The default value is already `undefined` we don't need to set it explicitly.

```suggestion
  quality,
```

**Comment by Heziode** [comment]
@frinyvonnick and what is the default value for type ?

Because if I only accept `png` or `jpe?g`, an `undefined` value will throw an error.

File: src/index.js [hunk 2]
```diff
@@ -15,6 +15,17 @@ module.exports = async function({
...
+  if (/jpe?g/.test(type)) {
+    if (!quality) {
+      screeshotArgs.quality = 80;
+      quality = 80
+    } else {
+      screeshotArgs.quality = quality;
+    }
+  } else if (type && type !== "png") {
+    throw Error(`Unknow type. Expected 'png','jpg','jpeg' got '${type}'`)
+  }
```
Comment (frinyvonnick) [inline src/index.js:28]: We don't need to check if the type is supported. Puppeteer already does it and throws an error.

File: src/index.js [hunk 3]
```diff
@@ -15,6 +15,17 @@ module.exports = async function({
   if (!html) {
     throw Error('You must provide an html property.')
   }
+  let screeshotArgs = {};
+  if (/jpe?g/.test(type)) {
```
Comment (frinyvonnick) [inline src/index.js:19]: As you can see in the documentation you linked earlier only png and jpeg are supported values. jpg is not valid.

```suggestion
  if (type === 'jpeg') {
```

File: src/index.js [hunk 4]
```diff
@@ -15,6 +15,17 @@ module.exports = async function({
...
+    if (!quality) {
+      screeshotArgs.quality = 80;
+      quality = 80
+    } else {
+      screeshotArgs.quality = quality;
+    }
```
Comment (frinyvonnick) [inline src/index.js:25]: A ternary could simplify this code a bit:

```suggestion
    screeshotArgs.quality = quality ? quality : 80
```

I also removed the line that set quality since it is not used afterwards.

File: src/index.js (hunk 2 above)
Comment (Heziode) [reply src/index.js]: Done by 3f15fd6

**Comment by Heziode** [comment]
When have you plan to release this fix ?

**Comment by frinyvonnick** [comment]
This has been published in [2.1.1](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v2.1.1) 🚀
